version: "3.8"
services:
    rabbitmq3:
        build: .
        container_name: "rabbitmq"
        image: rabbitmq:3-management-alpine
        ports:
            - '5673:5672'
            - '15672:15672'
        networks:
            - backend-network

    web:
        build: .
        image: web
        container_name: web
        ports:
          - 5000:5000
        command: python main.py run -h 0.0.0.0
        volumes:
            - .:/fabio-tests

    worker:
        build: .
        command: celery -A wikipedia worker -Q WIKI_QUEUE
        volumes:
            - .:/fabio-tests
        depends_on:
            - web
            - rabbitmq3

networks:
    backend-network:
        external: true