CREATE TABLE `continent` (
   `continent_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
   `name` VARCHAR(25) NOT NULL,
   `population` BIGINT UNSIGNED NOT NULL,
   `area` BIGINT UNSIGNED NOT NULL,
   `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY (`continent_id`),
   UNIQUE KEY (`name`)
);

CREATE TABLE `country` (
    `country_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(50) NOT NULL,
    `population` BIGINT UNSIGNED NOT NULL,
    `area` BIGINT UNSIGNED NOT NULL,
    `hospitals` INT UNSIGNED DEFAULT 0,
    `national_parks` INT UNSIGNED DEFAULT 0,
    `continent_id` INT UNSIGNED NOT NULL,
	`created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`country_id`),
    UNIQUE KEY (`name`),
    FOREIGN KEY (continent_id) REFERENCES continent(continent_id) ON DELETE CASCADE
);

CREATE TABLE `city` (
    `city_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(50) NOT NULL,
    `population` BIGINT UNSIGNED NOT NULL,
    `area` BIGINT UNSIGNED NOT NULL,
    `roads` INT UNSIGNED DEFAULT 0,
    `trees` INT UNSIGNED DEFAULT 0,
    `country_id` INT UNSIGNED NOT NULL,
	`created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`city_id`),
    UNIQUE KEY (`name`),
    FOREIGN KEY (country_id) REFERENCES country(country_id) ON DELETE CASCADE
);
